### ISSUE TITLE
[SIS-027] Blank Login Page

### ISSUE THREAD

**Issue by ramyzhang** [uoftblueprint/sistema#27]
> As a user of the Sistema Lesson Planner, I want to be able to view Sistema's logo and mission statement to better understand the organization while the app is loading!

**Technical Information:**

Create a new blank page for "Login" under a subdirectory of the main app with stand-in buttons for the login. Ignore the signup button for now.

![Image](https://user-images.githubusercontent.com/34625981/202334579-3f4c7ad5-8afd-492a-8fa3-897dbf775ae3.png)

**Colours:**

#FFFAF5
#685777
#4D8ECB

**Good Resources:**

You will need to use the React Native Elements library for UI components (images, buttons). Look at the code samples to figure out how to import and implement these elements!

[React Native UI Elements Library](https://reactnativeelements.com/)

**Comment by yuemily24** [comment]
Convert this to a loading page since we aren't doing login anymore.
