### ISSUE TITLE
[SIS-049] Get featured activity cards on home page

### ISSUE THREAD

**Issue by yuemily24** [uoftblueprint/sistema#49]
> As a user of the Sistema Lesson Planner, I want to be able to view recently added activity cards on the home page.

This is a 2-part ticket, a companion piece to [[SIS-048] Preview featured activity cards from the home page](https://github.com/uoftblueprint/sistema/issues/48). This is the back-end portion of it. 

For context, each week Alex uploads 2-8 new "featured" activity cards he wants teachers to use. These activity cards will often share a "theme". See how activity cards are named:

> Social Activity Cards have filenames with three parts:
> "Theme - Activity Type - Activity Title", for example "Listening - Knowledge - Listening Spinners"
> Theory and Musicianship Activity Cards have filenames with two parts:
> "Theme - Activity Type", for example "Harmony - Knowledge"

Although he sends out an email to all the teachers explaining the theme and pedagogy, we want teachers to be able to see it front and center on the home screen of the app as well--for easy viewing and as a reminder to use them.  

## Technical Information

Endpoints to implement:
`getFeaturedActivityCards`
`downloadActivityCard`

### getFeaturedActivityCards
**Description:** Returns an array of file paths for the themed activity cards featured this month. Finds the activity cards in the Sistema [Curriculum Materials](https://drive.google.com/drive/folders/1dki-Xc9XusQm86IvIjNC23Rv8rtQQTs-) folder and downloads them if they’re not cached.

**Discussion:** 

- Featured activity cards cards are located half Social Curriculum Activities (SCA), half in Theory and Musicianship Activities (TMA) (it’s always split between the two) subdirectories. Root folder we have access to is [Curriculum Materials](https://drive.google.com/drive/folders/1dki-Xc9XusQm86IvIjNC23Rv8rtQQTs-).
- Recommend storing these images in a specific directory in RNFS. Cache (download) the activity cards in there. Use `downloadActivityCard() ` in Searching. Might need to discuss with the other dev to work on helper function for this use case.
- How do we find the most recent activity cards on Drive? Check the upload pattern.
- How do we check that the cached cards are the ones for this month? Don’t assume that cached cards means that they are this month’s cards. 
- Don’t forget to remove last month’s cards if you’re downloading new ones. Use `deleteActivityCard()` in Searching.

#### Q&A with Alex

Confirm that all monthly themed activity cards can be found in the “Social Curriculum Activities” folder? 

- Half SCA, half in TMA → it’s always split between the two

Is there a new subfolder created each week?

- All the subfolders already exist, but some of them have not been populated. They’re being worked on over the year
- *Not all the Theory folders have been created yet

Ask about upload pattern → weekly, but is this on a strict schedule (i.e. always on Mondays?)

- Always doing it on Friday during the day (sends it out at the end of Friday for the teachers to prep for the following week)
- Schedule is set up so that this happens during months where there is full programming (e.g. December there is no programming because people are prepping for concert)

### downloadActivityCard
**Description:** Downloads an activity card from Drive. Returns a local path to the image.

**Discussion:** 
- @MinGi-K You can directly borrow this function to "Add Card" to lesson plan in your Search for Activity Card screen. 

## Resources

- Look at [wiki](https://github.com/uoftblueprint/sistema/wiki) and [Endpoint Reference](https://docs.google.com/document/d/1JdqTkQoUPN7ov9fGmf_vruavwfDfUzUdNY5I9AccnKQ/edit#).
- Definitely think out your strategy first before writing any code. Emily's suggestion: _Sort files in SCA and TMA subfolders. Grab date of latest activity card. Find activity cards that have been uploaded at that date._ Use Postman to test requests.
- Think about how we would cache. What are the use cases that would happen? See some discussion [here](https://docs.google.com/document/d/1JdqTkQoUPN7ov9fGmf_vruavwfDfUzUdNY5I9AccnKQ/edit?disco=AAAAi-xF-0o).
- What about the refresh button on the home page? How do we handle that? 
- Is there automatic sorting in the Drive API that we could utilize?

**Comment by yuemily24** [comment]
Please talk to @MinGi-K as you guys will both be working on searching for activity card issues. See [SIS-082](https://github.com/uoftblueprint/sistema/issues/82). You can likely share helper functions.

**Comment by yuemily24** [comment]
@harmitgoswami Added new endpoint to implement `downloadActivityCard`. Please review ticket for updates.

**Comment by ramyzhang** [comment]
@harmitgoswami Hey as you clean up this ticket, could you also work on the frontend connections? Please discuss with @MinGi-K on the activity card previews in order to display them in Home, maybe tag-team that or you could also just pick up that endpoint from him since Mingi's ticket is pretty heavy.
Also, please implement the "add activity card" button for downloading ACs :) Thanks!
