### ISSUE TITLE
[SIS-080] Library backend

### ISSUE THREAD

**Issue by yuemily24** [uoftblueprint/sistema#80]
> As a user of the Sistema Lesson Planner, I want to be able to view my lesson plans in the Library, as well as favorite them.

## Technical Information

Endpoints to implement: 
`getAllLessonPlans`
`favouriteLessonPlan` (new API) (watch the "u" in favourite) (we are a commonwealth nation here smh)

You will find these endpoints inside `LessonPlanService.js` under `/services/`. You can implement them following the example from the `deleteLessonPlan` endpoint; specifically, make sure that you're *not* calling the RNFS library directly in the function, but rather the required function from `Local.js` that will make the call to the library for you. Use the path constant from `constants.js` if you need access to a directory path constant as defined in the [documentation](https://github.com/itinance/react-native-fs#constants)!

Since you'll be working on the same file, `LessonPlanService.js` in tandem with @Lemiex and @kurtislaw, make sure to discuss with them for this ticket! We suggest starting a DM group chat together as you're starting your ticket. _Specifically, please discuss with each other how to implement the LessonPlan object specification in `/models/` because you'll be using it a lot in the service file!_

Questions on implementation? Missing functions in Local.js for RNFS calls that you need? DM the PLs!

## Local Storage Structure

In RNFS.DocumentDirectoryPath, establish 2 folders: `Default` and `Favourited`. Lesson Plans when first created should all go into the Default folder, and each lesson plan should create its own directory. 
> **Example:** `Default/LESSON_PLAN_NAME/`

In each lesson plan's directory, you'll have the .json file that details its contents, as well as its corresponding activity cards that the user attached to it.

When a lesson plan is favourited, move its directory into the `Favourited` folder. `Favourited` lesson plans are essentially pinned lesson plans, and should always be _displayed first_ in the UI, unless the user is sorting their lesson plans by name, or date, or whatever.

Things to consider and discuss with your ticket group (aka @Lemiex and @kurtislaw):
- How should we initialize the two directory paths `Default` and `Favourited`? Does RNFS automatically do it when we write to it with a path? Try it!
- What's the best way to return errors? How do you write more informative error messages?
- Are all moveFile() and related operations done recursively (a.k.a do all the contents of the directory move too?)

### getAllLessonPlanNames
**Description:** 
Return an array of all the lesson plan names that are currently in storage. Make sure to look inside _both_ the `Default` and `Favourited` directories, and return all the lesson plan names in the `Favourited` directory first in the array! If no lesson plans exist, error is thrown.

**Discussion:** 
Check the [wiki](https://github.com/uoftblueprint/sistema/wiki/Lesson-Plan-API) for more info, as well as the [Endpoint Reference](https://docs.google.com/document/d/1JdqTkQoUPN7ov9fGmf_vruavwfDfUzUdNY5I9AccnKQ/edit)!

### favouriteLessonPlan
**Description:** 
Given a LessonPlan object, move it into the `Favourited` directory. Be sure to check whether or not it exists already in the Default directory, and throw an error if it doesn't!

**Discussion:** 
Check the [wiki](https://github.com/uoftblueprint/sistema/wiki/Lesson-Plan-API) for more info, as well as the [Endpoint Reference](https://docs.google.com/document/d/1JdqTkQoUPN7ov9fGmf_vruavwfDfUzUdNY5I9AccnKQ/edit)! 

### unFavouriteLessonPlan
**Description:** 
Given a LessonPlan object, move it into the `Default` directory. check whether or not it exists already in the Favourited directory, and throw an error if it doesn't!

**Discussion:** 
Check the [wiki](https://github.com/uoftblueprint/sistema/wiki/Lesson-Plan-API) for more info, as well as the [Endpoint Reference](https://docs.google.com/document/d/1JdqTkQoUPN7ov9fGmf_vruavwfDfUzUdNY5I9AccnKQ/edit)! 

## Resources

Definitely think out your strategy first before writing any code. This ticket is in general very collaborative. Discuss with the Lesson Plan group: @Lemiex & @kurtislaw & @helenaglow 
[Official RNFS Documentation](https://github.com/itinance/react-native-fs)
[Testing RNFS](https://github.com/uoftblueprint/sistema/wiki/Testing-Local-Storage-Calls)

**Comment by ramyzhang** [comment]
@helenaglow new task: can you work on connecting your backend implementation to the frontend of the library page? i.e. display the activity cards and pin them as required when they're favourited?

**Comment by helenaglow** [comment]
> display the activity cards

Do you mean lesson plans?

**Comment by ramyzhang** [comment]
YES sorry!
