### ISSUE TITLE
[SIS-081] Export lesson plan to PDF

### ISSUE THREAD

**Issue by yuemily24** [uoftblueprint/sistema#81]
> As a user of the Sistema Lesson Planner, I want to be able to export my created lesson plans as PDF.

## Technical Information

You will be adding the feature for users to download a lesson plan (LP) as a PDF file. This button can be accessed in the Library. 

Convert the LP entity into a format that can be rendered into a PDF, such as HTML (I'm surmising here). You will likely have to find a package that can help you with essentially generating a PDF file, then exporting and downloading to your local storage on the phone (not RNFS). 

This ticket has quite a bit of flexibility and will require research. 

## Resources

Let us PLs know if you need opinions on what packages or options you're considering. 
Discuss with the Lesson Plan group on how they're storing the LP entity in the backend: @Lemiex & @kurtislaw & @helenaglow

**Comment by ramyzhang** [comment]
PS: You can access an Android's external storage on RNFS via RNFS.DownloadDirectoryPath or RNFS.ExternalDirectoryPath, but will likely need a diff package to access the iPhone's external storage
