### ISSUE TITLE
[SIS-082] Search activity cards backend

### ISSUE THREAD

**Issue by yuemily24** [uoftblueprint/sistema#82]
> As a user of the Sistema Lesson Planner, I want to be able to search for activity cards.

## Technical Information

Endpoints to implement: 
`searchActivityCards`
`getActivityCardPreview`

### searchActivityCards
**Description:** Given some user input, generate a list of activity cards in the Sistema [Curriculum Materials](https://drive.google.com/drive/folders/1dki-Xc9XusQm86IvIjNC23Rv8rtQQTs-) folder. Cap results at Constants.maxSearch which is an int determining the max number of suggested activity cards per search. Place this number in `constants.js` file. 

**Discussion:** 

- Typing in the Add Activity Card search bar should generate a list of results for this. I would ping the designers for how many search results you recommend displaying (see [UI](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=59%3A12896&t=VFmAxlq4E25Sw94q-0)) because 2 is too little. 
- Don't forget to search by the user's selected filters, which will be strings delimited by commas in the Drive file's description. We confirmed that this should automatically be counted in Drive's list but double check what happens when multiple filters are applied (enforce that filters are AND not OR). 
For Sistema, they edit tags here:
![image](https://user-images.githubusercontent.com/76456096/215311939-77686289-e628-43c2-8884-107a106ac37c.png)

### getActivityCardPreview
**Description:** Get a preview of a requested activity card from Drive and display it [here](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=59%3A13353&t=VFmAxlq4E25Sw94q-0). _Do not download the activity card to RNFS_. 

**Discussion:** 

- See [wiki](https://github.com/uoftblueprint/sistema/wiki/Search-API#getactivitycardpreviewid-string) and [Endpoint Reference](https://docs.google.com/document/d/1JdqTkQoUPN7ov9fGmf_vruavwfDfUzUdNY5I9AccnKQ/edit#) for prior discussion on this. 
- What information is needed from `searchActivityCards` to grab the exact file needed for preview?
- Please please ask us if you need clarification on what should be done for this ticket. We don't want you to assume things and make it harder for yourself. 

## Resources

Definitely think out your strategy first before writing any code. Talk to @harmitgoswami since you are both doing activity card searching. You can likely share functions.

**Comment by ramyzhang** [comment]
**Notes for future reference:** @MinGi-K @harmitgoswami 
- Only search within the "Performance Activities", "Social Curriculum Activities", and "Theory and Musicianship Activities" folders! Those are the only folders we care about.
- Activity cards will always either have a "Category - Theme - Activity" or "Theme - Activity" naming convention
- Some activity cards have "attachments" to them that you'll also want to add into the lesson plan, making that activity card a multi-page one. These activity cards will have an asterisk at the end of their filename (e.g. "Listening - Creation - Emo Echo*.jpg") and its attachments will be located in a folder of the same name in the same parent directory.
