### ISSUE TITLE
[SIS-090] Replace all colors with colors from colors constants file

### ISSUE THREAD

**Issue by ramyzhang** [uoftblueprint/sistema#90]
> As a user of the Sistema Lesson Planner, I want my app to be in a consistent colour palette!

## Technical Information

Small QoL micro-ticket!
- [ ] Replace all instances of colour hex code styling with variables from the colours constants file!

**Comment by yuemily24** [comment]
Quick question, what's the status on this?

**Comment by ramyzhang** [comment]
i think @MinGi-K 's working on it atm

**Comment by ramyzhang** [comment]
@helenaglow did you end up working on this? :0

**Comment by helenaglow** [comment]
No! I didnt even know I did that! oops! I must have done the wrong ticket sorry omg
