### ISSUE TITLE
[SIS-092] Review frontend

### ISSUE THREAD

**Issue by yuemily24** [uoftblueprint/sistema#92]
## Clean up screens
- [x] Home screen - Ramy
     - [x] Add Title splitting in `RecentCard` (see Figma for updated screen)
- [x] Editor - Ramy
     - [x] Redux state of the lesson plan - Sarah
     - [x] Delete module flow - Emily
     - [x] Sarah's ticket `saveLessonPlan` - Ramy
     - [x] Tap on text bug in editor - Ramy
     - [x] Android module shadow bug - Ramy
- [x] Library - Emily
- [x] Settings (make first)
- [x] Tutorial (make first) - Ramy
- [ ] Login - Emily

Please put your name next to the screen you are reviewing.

## Other tasks
- [x] fix linting errors
- [ ] link up all the overlay buttons and make sure the buttons in the overlay itself work as intended
- [x] icons
- [x] styling/padding <-- make sure it supports multiple devices
    - [ ] Do a review on all new screens and components added since
    - [ ] Search activity card screen and its components (ex. `NoCardsFound`, fix padding and change text styles). Basically [SIS-082 PR](https://github.com/uoftblueprint/sistema/pull/108/files)
- [ ] Colours config file (look at Mingi's PR)
    - [ ] Move hex codes from `RecentCard.js` into this
- [ ] Disable arrows in activity card search screen preview until someone handles [[SIS-129]](https://github.com/uoftblueprint/sistema/issues/129)

**Comment by ramyzhang** [comment]
- [x] make save button floating on editor

**Comment by ramyzhang** [comment]
- [x] little bump issue upon LP name editing is occurring on both android and ios now
